(define (domain smashdm)

	(:requirements
		:strips
	)


	(:predicates
		(addperson ?term1 ?term2 ?term3)
		(userstatus ?term1 ?term2)
		(devicestatus ?term1 ?term2)
		(planner--debug ?term1)
		(type ?term1 ?term2)
		(callertype ?term1 ?term2)
		(pl--goalachievecondition ?term1 ?term2 ?term3)
		(vl--isvalueimportant ?term1)
		(incomingcall ?term1 ?term2)
		(possiblephonestatus ?term1 ?term2 ?term3 ?term4 ?term5 ?term6 ?term7 ?term8)
		(standup ?term1)
		(vl--valueordering ?term1 ?term2 ?term3)
		(hasvaluename ?term1 ?term2)
		(personlocation ?term1 ?term2)
		(focusing ?term1 ?term2 ?term3 ?term4 ?term5 ?term6)
		(addphone ?term1 ?term2 ?term3 ?term4 ?term5)
		(vl--isvaluemoreimportantthan ?term1 ?term2)
		(possibletvstatus ?term1 ?term2 ?term3 ?term4 ?term5)
		(vl--isvaluenotimportant ?term1)
		(devicelocation ?term1 ?term2)
		(isvalueimportant ?term1)
		(kqml--bel_no_source_self ?term1 ?term2)
		(isvaluemoreimportantthan ?term1 ?term2)
		(vl--isvaluejustabove ?term1 ?term2)
		(addevent ?term1 ?term2 ?term3)
		(person ?term1)
		(standingup ?term1 ?term2)
		(focused ?term1 ?term2 ?term3)
		(gl--state ?term1 ?term2 ?term3)
		(device ?term1)
		(vl--defaultvaluejustabove ?term1 ?term2)
		(vl--debug ?term1)
		(deviceneighbor ?term1 ?term2)
		(hasworkingevent ?term1 ?term2)
		(isvaluenotimportant ?term1)
		(isvalueasimportantas ?term1 ?term2)
		(vl--isvaluelessimportantthan ?term1 ?term2)
		(al--debug ?term1)
		(addfurniture ?term1 ?term2)
		(isvaluelessimportantthan ?term1 ?term2)
		(importanceofvalues ?term1)
		(gl--debug ?term1)
		(vl--tests ?term1)
		(pl--debug ?term1)
		(workingstatus ?term1 ?term2)
		(sensing ?term1 ?term2)
		(devicemode ?term1 ?term2)
		(gl--goalimpact ?term1 ?term2 ?term3)
		(addtv ?term1 ?term2 ?term3 ?term4)
		(joined ?term1 ?term2)
		(isvaluemostimportant ?term1)
		(vl--isvaluemostimportant ?term1)
		(isvalueleastimportant ?term1)
		(vl--isvalueasimportantas ?term1 ?term2)
		(demo--demo ?term1)
		(deviceowner ?term1 ?term2)
		(joinedwsp ?term1 ?term2 ?term3)
		(sittingon ?term1 ?term2)
		(kqml--clear_source_self ?term1 ?term2)
		(vl--isvalueleastimportant ?term1)
		(setphonestatus ?term1 ?term2)
		(settvstatus ?term1 ?term2)
		(outcomingcall ?term1 ?term2)
		(gl--goalactivation ?term1 ?term2 ?term3)
	)

	(:action setTVStatus
		:parameters (?tv ?status)
		:precondition (and (not (devicestatus ?tv ?status)) (type ?tv _q1q_tv_q1q_))
		:effect (devicestatus ?tv ?status)
	)

	(:action setPhoneStatus
		:parameters (?phone ?status)
		:precondition (and (not (devicestatus ?phone ?status)) (type ?phone _q1q_phone_q1q_))
		:effect (devicestatus ?phone ?status)
	)

)